services:
  db:
    build: ./db
    container_name: mdblog-db-container
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpass
      POSTGRES_DB: main
    ports:
      - "5433:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

    restart: unless-stopped

